// API endpoint for deploying websites to GitHub and Vercel
import { NextRequest, NextResponse } from "next/server";
import { logError, logInfo } from "@/lib/log";
import { z } from "zod";
import { getUser } from "@/lib/auth/getUser";
import { getSiteById, updateSite } from "@/data/sites";
import { GitHubClient } from "@/lib/clients/github";
import { VercelProvider } from "@/lib/providers/impl/vercel";

const DeployToVercelSchema = z.object({
  siteId: z.string().min(1, "Site ID is required"),
});

export async function POST(req: NextRequest) {
  try {
    const user = await getUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const { siteId } = DeployToVercelSchema.parse(body);

    logInfo('Starting deployment to GitHub and Vercel', { siteId });

    // Get the site with its files
    const site = await getSiteById(siteId, user.id);
    if (!site) {
      return NextResponse.json({ error: "Site not found" }, { status: 404 });
    }

    // Get website files from websiteContent
    const files = site.websiteContent?.files || site.websiteContent || {};
    if (!files || Object.keys(files).length === 0) {
      return NextResponse.json({ error: "No website files found" }, { status: 400 });
    }

    let repoUrl: string | undefined;
    let previewUrl: string;

    try {
      // Step 1: Deploy to GitHub
      logInfo('Deploying to GitHub', { siteId, siteName: site.name });
      const github = new GitHubClient();
      
      // Create repository
      repoUrl = await github.createRepository(site.name, `Generated website for ${site.name}`);
      
      // Extract repo name from URL
      const repoName = repoUrl.replace('https://github.com/', '');
      
      // Add vercel.json for instant static deployment (no build step)
      const vercelConfig = {
        version: 2,
        public: true,
        builds: [{ src: "**/*", use: "@vercel/static" }],
        routes: [{ handle: "filesystem" }]
      };
      
      // Files for GitHub (includes vercel.json)
      const githubFiles = {
        ...files,
        'vercel.json': JSON.stringify(vercelConfig, null, 2),
        'package.json': JSON.stringify({
          name: site.slug,
          version: '1.0.0',
          scripts: {
            dev: 'npx serve .',
            start: 'npx serve .'
          },
          dependencies: {}
        }, null, 2)
      };
      
      // Files for Vercel (vercel.json is added by the provider)
      const vercelFiles = {
        ...files,
        'package.json': JSON.stringify({
          name: site.slug,
          version: '1.0.0',
          scripts: {
            dev: 'npx serve .',
            start: 'npx serve .'
          },
          dependencies: {}
        }, null, 2)
      };
      
      // Push files to GitHub
      await github.pushFiles(repoName, githubFiles, `Initial commit - Generated by Avallon for ${site.name}`);
      
      logInfo('Successfully deployed to GitHub', { repoUrl });

      // Step 2: Deploy to Vercel
      logInfo('Deploying to Vercel', { siteId, repoUrl });
      const vercel = new VercelProvider();
      const projectName = site.slug;
      
      // Create Vercel project
      const project = await vercel.createProject({
        name: projectName,
        framework: 'static',
        rootDirectory: ''
      });
      
      logInfo('Vercel project created', { projectId: project.projectId });
      
      // Deploy files directly to Vercel (not via Git - simpler and doesn't require Git integration)
      const deployment = await vercel.createDeployment({
        projectId: project.projectId,
        files: vercelFiles
      });
      
      logInfo('Vercel deployment created', { deploymentId: deployment.deploymentId, url: deployment.url });
      
      // Wait a bit for deployment to process
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Get deployment status
      const status = await vercel.getDeploymentStatus(deployment.deploymentId);
      previewUrl = status.url || deployment.url;
      
      logInfo('Vercel deployment completed', { previewUrl });

      // Update the site with deployment URLs
      await updateSite(siteId, user.id, {
        repoUrl,
        previewUrl,
        vercelProjectId: project.projectId,
        vercelDeploymentId: deployment.deploymentId,
        status: 'live'
      });

      return NextResponse.json({
        success: true,
        previewUrl,
        repoUrl,
        message: "Website deployed successfully!"
      });
    } catch (deployError: any) {
      logError('Deployment failed', deployError);
      return NextResponse.json({
        error: "Deployment failed",
        details: deployError.message
      }, { status: 500 });
    }
  } catch (error: any) {
    logError('Vercel deployment failed', error);
    if (error.name === 'ZodError') {
      return NextResponse.json({ error: "Invalid input", details: error.errors }, { status: 400 });
    }
    return NextResponse.json({ error: "Internal server error", details: error.message }, { status: 500 });
  }
}
