// CHANGELOG: 2025-01-15 - Mock site generation test to demonstrate complete workflow
import { NextResponse } from "next/server";
import axios from "axios";

export async function GET() {
  try {
    const githubToken = process.env.GITHUB_TOKEN;
    const githubOrg = process.env.GITHUB_ORG;
    
    if (!githubToken) {
      return NextResponse.json({ 
        error: "GitHub token not configured" 
      }, { status: 400 });
    }

    const siteName = "test-site-" + Date.now();
    const repoName = siteName.toLowerCase().replace(/\s+/g, '-');
    
    // Step 1: Create mock site files
    const mockFiles = {
      'package.json': JSON.stringify({
        name: repoName,
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start'
        },
        dependencies: {
          'next': '14.0.0',
          'react': '^18.0.0',
          'react-dom': '^18.0.0',
          'typescript': '^5.0.0',
          'tailwindcss': '^3.0.0'
        }
      }, null, 2),
      'app/page.tsx': `export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="container mx-auto px-4 py-16">
        <h1 className="text-4xl font-bold text-center text-gray-900 mb-8">
          Welcome to ${siteName}
        </h1>
        <p className="text-xl text-center text-gray-600 max-w-2xl mx-auto">
          This is a mock site generated by Avallon Cloud to demonstrate the complete workflow.
        </p>
      </div>
    </div>
  );
}`,
      'app/layout.tsx': `import './globals.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
      'app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;`,
      'README.md': `# ${siteName}

This is a mock site generated by Avallon Cloud.

## Features
- Next.js 14
- TypeScript
- Tailwind CSS
- Responsive design

Generated on ${new Date().toISOString()}
`
    };

    // Step 2: Create GitHub repository
    let repoUrl = '';
    try {
      const createRepoResponse = await axios.post(
        'https://api.github.com/user/repos',
        {
          name: repoName,
          description: `Mock site generated by Avallon Cloud - ${siteName}`,
          private: false,
          auto_init: false
        },
        {
          headers: {
            'Authorization': `Bearer ${githubToken}`,
            'Accept': 'application/vnd.github.v3+json'
          }
        }
      );
      
      repoUrl = createRepoResponse.data.html_url;
    } catch (error: any) {
      if (error.response?.status === 422) {
        // Repository already exists, that's okay
        repoUrl = `https://github.com/${githubOrg}/${repoName}`;
      } else {
        throw error;
      }
    }

    // Step 3: Push files to GitHub
    const fullRepoName = `${githubOrg}/${repoName}`;
    
    // Get the default branch
    const repoResponse = await axios.get(
      `https://api.github.com/repos/${fullRepoName}`,
      {
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json'
        }
      }
    );
    
    const defaultBranch = repoResponse.data.default_branch;
    
    // Create tree with all files
    const tree = Object.entries(mockFiles).map(([path, content]) => ({
      path,
      mode: '100644',
      type: 'blob',
      content: Buffer.from(content).toString('base64')
    }));
    
    const treeResponse = await axios.post(
      `https://api.github.com/repos/${fullRepoName}/git/trees`,
      { tree },
      {
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json'
        }
      }
    );
    
    // Create commit
    const commitResponse = await axios.post(
      `https://api.github.com/repos/${fullRepoName}/git/commits`,
      {
        message: 'Initial commit - Mock site generated by Avallon Cloud',
        tree: treeResponse.data.sha
      },
      {
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json'
        }
      }
    );
    
    // Update branch reference
    await axios.patch(
      `https://api.github.com/repos/${fullRepoName}/git/refs/heads/${defaultBranch}`,
      {
        sha: commitResponse.data.sha
      },
      {
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json'
        }
      }
    );

    return NextResponse.json({
      success: true,
      message: "🎉 Mock site generation completed!",
      site: {
        name: siteName,
        repoName,
        repoUrl,
        files: Object.keys(mockFiles),
        status: "Repository created and code pushed successfully"
      },
      workflow: {
        step1: "✅ Mock site code generated",
        step2: "✅ GitHub repository created",
        step3: "✅ Code pushed to GitHub",
        step4: "⏳ Vercel deployment (requires Vercel token)"
      }
    });

  } catch (error: any) {
    return NextResponse.json({
      error: "Mock site generation failed",
      details: error.message,
      status: error.response?.status,
      responseData: error.response?.data
    }, { status: 500 });
  }
}
