// Mock Supabase client to prevent authentication errors
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://mock.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'mock-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a mock client that doesn't actually connect to Supabase
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Override auth methods to prevent errors
supabase.auth.getSession = () => Promise.resolve({ data: { session: null }, error: null });
supabase.auth.onAuthStateChange = () => ({ data: { subscription: { unsubscribe: () => {} } } });
supabase.auth.signOut = () => Promise.resolve({ error: null });