// GitHub API client for creating repositories and pushing files
import axios from 'axios';
import { logError, logInfo } from '@/lib/log';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN || '';
const GITHUB_OWNER = process.env.GITHUB_OWNER || '';

export class GitHubClient {
  private getHeaders() {
    return {
      'Authorization': `Bearer ${GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    };
  }

  async createRepository(name: string, description: string = ''): Promise<string> {
    if (!GITHUB_TOKEN || !GITHUB_OWNER) {
      throw new Error('GITHUB_TOKEN and GITHUB_OWNER must be set in environment variables');
    }

    const repoName = name.toLowerCase().replace(/\s+/g, '-');
    const fullRepoName = `${GITHUB_OWNER}/${repoName}`;

    try {
      logInfo('Creating GitHub repository', { fullRepoName });

      // Check if repo already exists
      try {
        await axios.get(`https://api.github.com/repos/${fullRepoName}`, {
          headers: this.getHeaders()
        });
        logInfo('Repository already exists, will update', { fullRepoName });
        return `https://github.com/${fullRepoName}`;
      } catch (error: any) {
        if (error.response?.status !== 404) {
          throw error;
        }
      }

      // Create new repository
      await axios.post(
        'https://api.github.com/user/repos',
        {
          name: repoName,
          description: description || `Generated website for ${name}`,
          private: false,
          auto_init: false
        },
        { headers: this.getHeaders() }
      );

      logInfo('GitHub repository created', { fullRepoName });
      return `https://github.com/${fullRepoName}`;
    } catch (error: any) {
      logError('GitHub createRepository error', error, { name, fullRepoName });
      throw new Error(`Failed to create GitHub repository: ${error.message}`);
    }
  }

  async pushFiles(repoName: string, files: Record<string, string>, commitMessage: string = 'Initial commit - Generated by Avallon'): Promise<void> {
    if (!GITHUB_TOKEN) {
      throw new Error('GITHUB_TOKEN must be set');
    }

    try {
      logInfo('Pushing files to GitHub using Contents API', { repoName, fileCount: Object.keys(files).length });

      // Use GitHub Contents API - simpler and works with empty repos
      for (const [path, content] of Object.entries(files)) {
        try {
          // Check if file exists (to get SHA for updates)
          let existingSha: string | undefined;
          try {
            const existingFile = await axios.get(
              `https://api.github.com/repos/${repoName}/contents/${path}`,
              { headers: this.getHeaders() }
            );
            existingSha = existingFile.data.sha;
            logInfo('File exists, will update', { path, sha: existingSha });
          } catch (e: any) {
            // File doesn't exist, that's fine
            logInfo('File does not exist, will create', { path });
          }

          // Create or update file
          const payload: any = {
            message: existingSha ? `Update ${path}` : commitMessage,
            content: Buffer.from(content).toString('base64')
          };
          
          if (existingSha) {
            payload.sha = existingSha;
          }

          await axios.put(
            `https://api.github.com/repos/${repoName}/contents/${path}`,
            payload,
            { headers: this.getHeaders() }
          );
          
          logInfo('File pushed successfully', { path });
        } catch (fileError: any) {
          logError('Failed to push file', fileError, { path, status: fileError.response?.status });
          throw fileError;
        }
      }

      logInfo('All files pushed to GitHub successfully', { repoName, fileCount: Object.keys(files).length });
    } catch (error: any) {
      logError('GitHub pushFiles error', error, { repoName });
      throw new Error(`Failed to push files to GitHub: ${error.message}`);
    }
  }

  private async createInitialCommit(repoName: string, files: Record<string, string>, message: string): Promise<string> {
    // Create tree
    const tree = await this.createGitTree(repoName, files);
    
    // Create commit without parent
    const commitResponse = await axios.post(
      `https://api.github.com/repos/${repoName}/git/commits`,
      {
        message,
        tree: tree.sha
      },
      { headers: this.getHeaders() }
    );
    
    // Create main branch
    await axios.post(
      `https://api.github.com/repos/${repoName}/git/refs`,
      {
        ref: 'refs/heads/main',
        sha: commitResponse.data.sha
      },
      { headers: this.getHeaders() }
    );
    
    return commitResponse.data.sha;
  }

  private async createGitTree(repoName: string, files: Record<string, string>): Promise<any> {
    const tree = Object.entries(files).map(([path, content]) => ({
      path,
      mode: '100644',
      type: 'blob',
      content: content // Raw content - GitHub API handles encoding
    }));
    
    const response = await axios.post(
      `https://api.github.com/repos/${repoName}/git/trees`,
      { tree },
      { headers: this.getHeaders() }
    );
    
    return response.data;
  }

  static isConfigured(): boolean {
    return !!(GITHUB_TOKEN && GITHUB_OWNER);
  }
}

